- src/generated-client.js
- templates/generated-client.js.hbs
This modifies the template to be aware of the schema of the response.  If there is no schema for the response, we assume it should not be parsed as JSON.  Otherwise, assume it is a JSON response.
> Only parse JSON responses if we need to

- okta.yaml
- src/config-loader.js
- test/unit/config-loader.js
- 🌱  Includes default `okta.yaml` to ease onboarding
- :fire: Changes YAML parsing to include `okta` root.
- ✅  Updates config tests
> Updates YAML format to include 'okta' root

- src/resource.js
- test/unit/reesource.js
Explicitly setting to false is not necessary.  Closes #32.  Thanks @d-asensio  !
> Update enumerable definition on resource class

- .gitignore
- package-lock.json
- package.json
* Cron job is failing after adding junit reporter - https://travis-ci.org/okta/okta-sdk-nodejs/builds/407885467
* Test results are not shown on command line as well 
* Passing cron job with this revert - https://travis-ci.org/okta/okta-sdk-nodejs/jobs/407889850
* Will figure out another way to report results on bacon. junit xml only helps provide test numbers on bacon UI (passed/failed) We could sacrifice this small benefit and instead go through the bacon logs to find out test results.
> Reverting junit reporter change

- test/it/application-get-group-assignment.js
- test/it/application-group-assignment-delete.js
- test/it/application-list-group-assignments.js
- test/it/application-update-group-assignment.js
- test/it/application-update.js
- test/it/client-delete-group-application-assignment.js
- test/it/client-get-group-application-assignment.js
- test/it/client-list-application-group-assignment.js
- test/it/client-list-users.js
- test/it/client-update-application.js
- test/it/client-update-group-application-assignment.js
Also removes common group names in tests (which sometimes leads to resource already exists error)
> Updates client.listUsers() test

- test/it/client-update-application.js
- test/it/group-rule-operations.js
* Using `faker.random.words()` in tests sometimes causes the following error - 
` Okta HTTP 400 E0000001 Api validation failed: name. name: The field is too long`
* Failed build - https://travis-ci.org/okta/okta-sdk-nodejs/jobs/416135114
> Fixes API validation failure in tests

- test/it/client-create-application.js
* Tests against trex are currently failing - https://travis-ci.org/okta/okta-sdk-nodejs/builds
* The issue is related to app resource name already existing in DB 
* Adding a random word to app label fixes this
> Fixes failing client create application test

- package-lock.json
- package.json
Internal PR for #90 so that tests can run
- npm audit checks security vulnerabilities.
- It found 256, 223 only needed patch bumps.
- The remaining need major or minor version bumps.
> Ran `npm audit fix` on okta-sdk-node-js for 223 vulns ( for #90)

- CHANGELOG.md
- README.md
- src/client.js
- test/jest/client.test.js
This is a change that we intended to make in the next major version
> Use the DefaultRequestExecutor by default

- .gitignore
- README.md
- docs/JSDOC.md
Copied from https://github.com/okta/okta-sdk-nodejs/pull/99
**Description**
Pls see https://oktainc.atlassian.net/browse/OKTA-223863 for snapshots
**Fixes**
- Typo - interactions*
- Added hyperlink to Client.html
- Added "," to JS example
> Some jsdocs fixes

- test/it/policies.js
* Policy tests failing on travis due to "Resource already exists" error
* Introducing a random word in resource names fixes this issue, in case resource cleanup doesn't happen
> Updates policy tests to use random names

- src/collection.js
- templates/generated-client.js.hbs
- test/unit/collection.js
Description:
Pass fetch request object into Collection's constructor to pass request to httpClient.
Resolves: OKTA-288633
> fix: templates to pass request to Collection constructor - OKTA-288633

- test/unit/config-loader.js
Config loader unit test failed in travis because of unit tests was affected by travis build env variables. This pr created proper mock to isolate unit test environment.
Resolves: OKTA-295995
> Fix unit test okta 295995

- test/it/mocks/user-type.json
- test/it/type-user.js
Paths covered in this PR:
* /api/v1/meta/types/user
* /api/v1/meta/types/user/${typeId}
> test: add it for user type api - OKTA-288654

- test/it/linked-object.js
- test/it/mocks/linked-object.json
Paths covered in this PR:
* /api/v1/meta/schemas/user/linkedObjects
* /api/v1/meta/schemas/user/linkedObjects/${linkedObjectName}
* /api/v1/users/${userId}/linkedObjects/${relationshipName}
* /api/v1/users/${associatedUserId}/linkedObjects/${primaryRelationshipName}/${primaryUserId}
> Integration tests for linked object api okta 288651

- test/it/group-app.js
- test/it/mocks/group.json
After comparing with existing tests for group API. Looks like the only missing tests are for listAssignedApplicationsForGroup `/api/v1/groups/${groupId}/apps`
> test: add it for group api - OKTA-288652

- test/it/mocks/group.json
- test/it/mocks/okta-sign-on-policy.json
- test/it/mocks/policy-deny-rule.json
- test/it/policy-crud.js
- test/it/policy-lifecycle.js
- test/it/policy-rule.js
APIs covered in this PR:
* /api/v1/policies
* /api/v1/policies/${policyId}
* /api/v1/policies/${policyId}/lifecycle/activate
* /api/v1/policies/${policyId}/lifecycle/deactivate
* /api/v1/policies/${policyId}/rules
* /api/v1/policies/${policyId}/rules/${ruleId}
* /api/v1/policies/${policyId}/rules/${ruleId}/lifecycle/activate
* /api/v1/policies/${policyId}/rules/${ruleId}/lifecycle/deactivate
> integration tests for policy api okta 288650

- CHANGELOG.md
- package.json
- src/client.js
- src/http.js
- src/jwt.js
- src/oauth.js
- test/jest/http.test.js
- test/jest/jwt.test.js
- test/jest/oauth.test.js
What's in this PR:
- add refresh access token strategy
- fix error if token is not provided in configure when `authorizationMode` is `PrivateKey`
Fixes  #135
> feat: handle access token refresh - OKTA-291504

- test/it/idp-credential.js
Due to keys limitation per org, disable some key related test suites.
> test: skip csr test suites

- CHANGELOG.md
- package.json
- src/factories/UserFactorFactory.js
- src/generated-client.js
- src/models/AcsEndpoint.js
- src/models/CustomHotpUserFactor.js
- src/models/CustomHotpUserFactorProfile.js
- src/models/SamlApplicationSettingsSignOn.js
- src/models/index.js
- templates/generated-client.js.hbs
- templates/helpers/operation.js
- test/utils.js
- yarn.lock
> feat: support required params validation - OKTA-332240

- package.json
- yarn.lock
converted from #201 to allow CI tests to pass.
Original description:
The older version of isomorphic-fetch uses the older version of node-fetch, which has the following reported vulnerability: snyk.io/vuln/SNYK-JS-NODEFETCH-674311
> Bump the version of isomorphic-fetch

- CHANGELOG.md
- package.json
- yarn.lock
- upgrade isomorphic-fetch for security vuln [203](https://github.com/okta/okta-sdk-nodejs/pull/203)
> okta 334109 release 4.1.2

- package.json
- scripts/validate.js
- test/it/application-user-schema.ts
- test/it/authserver-crud.ts
- test/it/authserver-scope.ts
- test/it/client-get-logs.ts
- test/it/client-list-application-group-assignment.ts
- test/it/client-list-application-users.ts
- test/it/client-list-applications.ts
- test/it/client-list-users.ts
- test/it/group-rule-operations.ts
- test/it/group-search.ts
- test/it/idp-crud.ts
- test/it/mocks/generic-oidc-idp.js
- test/it/network-zone.ts
- test/it/trusted-origin.ts
- test/it/user-list-enrolled-factors.ts
- test/it/user-schema.ts
- test/it/user-type-api.ts
- yarn.lock
Internal ref: OKTA-512396
- Added filter and pagination integration tests
- Added `yarn validate:v2-v3` to catch v2 vs v3 specs incompatibility. 
Found issues:
- `listIdentityProviders` - `type` and `q` does not work (server issue)
- `listUsers` - using  `q` produces error (query params incompatibility in v2 vs v3 specs)
- `listGroups` - using  `search` and `limit` produces error (query params incompatibility in v2 vs v3 specs)
- `listApplications` - `includeNonDeleted` has no effect (spec issue)
- `listAuthorizationServers` - `limit` should be number, not string (spec issue)
- `listOrigins` - pagination with `q` works incorrectly, `q` is replaced with `filter` in `next` link (server issue)
- `listOAuth2Scopes` - `filter`, `limit`, `after` does not work and not documented (spec issue?) …
> Added filter and pagination integration tests

- package.json
- src/client.js
- src/types/client.d.ts
- test/it/device-api.ts
- test/it/push-provider-api.ts
Internal ref: OKTA-602351
Resolves #386
> Add Device Api

- CHANGELOG.md
- src/generated/servers.js
- templates/openapi-generator/http/servers.mustache
- test/jest/servers.test.js
Special characters in path parameters are not encoded.
Example:
```js
await client.userApi.getUser({
userId: 'test#user@okta.com'
});
```
Request is sent to `https://mydomain.com/api/v1/users/test#user@okta.com`
Issue Number: [OKTA-618059](https://oktainc.atlassian.net/browse/OKTA-618059), [OKTA-609249](https://oktainc.atlassian.net/browse/OKTA-609249)
Request is sent to `https://mydomain.com/api/v1/users/test%23user%40okta.com`
> fix: Encode special characters in path parameters

- CHANGELOG.md
- package.json
- yarn.lock
> fix: CVE 2024 34273
