okta/okta-sdk-nodejs

package.json

This should have been there to begin with

Move lodash to prod deps

---

test/it/client-listUsers.js
test/it/group-get.js
test/it/group-list.js
test/it/group-rule-operations.js
test/it/group-search.js
test/it/group-update.js
test/it/group-user-operations.js
test/it/user-activate.js
test/it/user-assign-role.js
test/it/user-change-password.js
test/it/user-change-recovery-question.js
test/it/user-expire-password.js
test/it/user-get-reset-password-url.js
test/it/user-get.js
test/it/user-group-target-role.js
test/it/user-profile-update.js
test/it/user-suspend.js
test/utils.js

1. Added checks to ensure that entities are deleted after delete is called (404 error is thrown)
2. Cleanup is now called conditionally at the end of each test -> Run only if testing against real server
3. Updated ‘user profile update’ test to ensure profile updated with an extra get call
4. Update ‘expire user password’ test to check that tempPassword is returned after calling expire password
5. Updated the client-listUsers.js test to use async/await

Test updates

---

scripts/setup.sh

Need this for publish task to complete successfully (changes directory into the correct parent)

Add setup script for bacon

---

src/collection.js
test/unit/collection.js

fix: empty results in collection.each()

---

src/generated-client.js
src/models/AppUser.js
src/models/Application.js
src/models/ApplicationGroupAssignment.js
src/models/Factor.js
src/models/Group.js
src/models/GroupRule.js
src/models/Session.js
src/models/User.js
templates/index.js
templates/model.js.hbs

* Changes to the templates to build JsDoc annotations for model methods
* Includes new built src with these template changes

Add JsDoc to model methods

---

package.json

Manual this time rev due to ci update changes

Rev package.json to 1.2.0

---

README.md
src/collection.js

Duplicate PR of #82, pushed to a branch in this repo so that all tests can run

Enable async iteration on any Collection (for #82)

---

README.md

Pulled from https://github.com/okta/okta-sdk-nodejs/pull/101
Pls see JIRA - https://oktainc.atlassian.net/browse/OKTA-224249 for links and snapshots
- [OKTA-224249](https://oktainc.atlassian.net/browse/OKTA-224249)

Fixes for Application hyperlinks in jsdocs

---

package-lock.json
package.json
test/it/client-list-users.js

- Moves @okta/openapi to devDependencies
- fixes a linting failure in the integration tests

fix(build): Moves openapi to devdeps; fixes test lint

---

scripts/publish.sh

We don't want to hard code this URL

Use npm registry value from environment var

---

README.md

Related GH issue: https://github.com/okta/okta-sdk-nodejs/issues/76

doc: call other API endpoints

---

templates/index.js

Fix templates generator to resolve lint issues.
Lint issue reported in console: (2nd one should be resolved [here](https://github.com/okta/openapi/pull/192#discussion_r392509479))
```
/Users/shuowu/devex/okta-sdk-nodejs/src/generated-client.js
914:28  error  'jwkUse' is defined but never used  no-unused-vars
/Users/shuowu/devex/okta-sdk-nodejs/src/models/AuthorizationServer.js
105:3  error  Duplicate name 'revokeAuthorizationServerAndClientTokens'  no-dupe-class-members
/Users/shuowu/devex/okta-sdk-nodejs/src/models/OAuth2ClaimConditions.js
26:25  error  A constructor name should not start with a lowercase letter  new-cap
```

fix: templates generator

---

src/generated-client.js
templates/generated-client.js.hbs
templates/index.js

Fix generated args for `x-okta-multi-operations`

fix: support x-okta-multi-operation - OKTA-289242

---

src/generated-client.js
templates/generated-client.js.hbs
templates/helpers/operation.js
test/it/authserver-claim.js
test/it/authserver-credential.js
test/it/authserver-crud.js
test/it/authserver-lifecycle.js
test/it/authserver-policy.js
test/it/authserver-scope.js
test/it/mocks/authorization-server.json
test/it/mocks/claim.json
test/it/mocks/policy-oauth-authorization.json
test/it/mocks/scope.json

- All ITs added in this PR for auth server have been marked with `skip` due to signing key limitation issues per org. ITs work properly when targeting to my dev org which has not reached the key limitation.
- Fix template generator to add body to request for Collection call. Tests all passed locally.

test: add ITs for auth server - OKTA-288644

---

test/it/user-list-available-factors.js

Most factor tests have already been added. Just enable one skipped test in this PR.

test: enable skipped factor test - OKTA-288643

---

test/it/application-grant.js
test/it/application-token.js
test/it/mocks/application-oidc.json

Add missing tests for:
* /apps/${appId}/tokens
* /apps/${appId}/grants

test: add it for application - OKTA-288642

---

test/it/application-get-group-assignment.js
test/it/application-group-assignment-delete.js
test/it/application-list-group-assignments.js
test/it/application-update-group-assignment.js
test/it/client-create-application.js
test/it/client-delete-group-application-assignment.js
test/it/client-get-group-application-assignment.js
test/it/client-list-application-group-assignment.js
test/it/client-update-group-application-assignment.js
test/it/group-get.js
test/it/group-list.js
test/it/group-rule-operations.js
test/it/group-search.js
test/it/group-update.js
test/it/group-user-operations.js
test/it/policies.js
test/it/user-group-target-role.js

* Fixes some intermittent nighly test failures

Adds node sdk prefix and unique resource names in tests

---

.travis.yml
test/it/client-list-applications.js

* Runs builds for node 10, 12 in parallel
* Removed the limit on number of parallel jobs in travis setting (not in this PR)

test: runs builds in parallel

---

package.json
yarn.lock

https://www.npmjs.com/package/flat/v/2.0.1
https://github.com/okta/okta-sdk-nodejs/issues/195

updates dependency "flat"

---

CHANGELOG.md
src/generated-client.js
templates/index.js
test/it/user-expire-password.js

* fix: url generation issue - OKTA-317349
* Adds expire password test
* chore: bump version and add changelog
Co-authored-by: Vijet Mahabaleshwar <vijet.mahabaleshwar@okta.com>

fix: url generation issue - OKTA-317349 (#180)

---

README.md

It reports "Okta API token not provided" using previous client config

Fix client config in readme

---

CHANGELOG.md
package.json
yarn.lock

release 3.3.2

---

CHANGELOG.md

release: 4.2

---

CHANGELOG.md
package.json
src/generated-client.js
templates/index.js
test/it/user-expire-password.js

cherry pick 2c0f717eab2f5607812c9b99ef8e0092513478db to 4.2 branch

Cherry pick hbs fix to 4.2 (#180)

---

templates/swagger-codegen/errata.json

[OKTA-483661](https://oktainc.atlassian.net/browse/OKTA-483661)

Preserve correct model property names

---

src/client.js
src/generated-client.js
src/types/client.d.ts
src/types/generated-client.d.ts
templates/helpers/operation-v3.js
test/it/threat-insight.ts

Internal ref:
https://oktainc.atlassian.net/browse/OKTA-453792
https://oktainc.atlassian.net/browse/OKTA-453793

Integrate ThreatInsight API into v2 client

---

src/client.js
src/generated-client.js
src/generated/models/ObjectSerializer.js
src/types/client.d.ts
src/types/generated-client.d.ts
src/types/models/UserFactor.d.ts
templates/generated-client.js.hbs
templates/helpers/operation-v3.js
templates/helpers/operation.js
templates/index.js
templates/openapi-generator/model/ObjectSerializer.mustache
test/it/factor-activate.ts
test/it/factor-create.ts
test/it/factor-delete.ts
test/it/factor-verify.ts
test/it/user-list-available-factors.ts
test/it/user-list-enrolled-factors.ts

Integrate User Factor API

---

src/generated-client.js
src/types/generated-client.d.ts
templates/helpers/operation-v3.js
test/it/application-csr.ts

Internal ref: [OKTA-515263](https://oktainc.atlassian.net/browse/OKTA-515263)

Add integration tests for application certificates operations

---

package.json
test/delete-resources.js
test/it/application-csr.ts
test/it/subscription-role.ts
test/it/subscription-user.ts

Fix integration tests conversion artifacts

---

CHANGELOG.md
README.md
src/index.js
src/types/index.d.ts
src/types/memory-store.d.ts
test/it/application-user-schema.ts
test/type/memory-store.test-d.ts

fix: export MemoryStore through library root, update MemoryStore.get type signature

---

CHANGELOG.md
package.json
src/types/custom-attributes.d.ts
src/types/models/GroupProfile.d.ts
src/types/models/InlineHookPayload.d.ts
src/types/models/SmsTemplateTranslations.d.ts
src/types/models/UserProfile.d.ts
templates/model.d.ts.hbs
test/type/user-profile.test-d.ts
yarn.lock

fix: allow custom attributes for extensible types

---

test/delete-resources.ts
test/it/domain-api.ts

Fix e2e tests for Custom Domains API

---

scripts/e2e.sh
scripts/unit.sh
test/delete-resources.ts
test/it/domain-api.ts

Uses secrets from Vault for test suites

---

scripts/clean-resources.sh
scripts/e2e.sh
scripts/unit.sh
test/delete-resources.ts
test/it/application-provisioning-connection.ts
test/it/feature-crud.ts
test/it/mocks/device-assurance-policy.js
test/it/network-zone.ts
test/it/session-refresh.ts
test/it/user-change-recovery-question.ts

Fix e2e tests

---

CHANGELOG.md
package.json
yarn.lock

fix: upgrades form-data
